name: Deploy to github pages

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore  MdIcons.Blazor/MdiIcons.Blazor.Sample/MdiIcons.Blazor.Sample.csproj 
    - name: publish 
      run:  dotnet publish  MdIcons.Blazor/MdiIcons.Blazor.Sample/MdiIcons.Blazor.Sample.csproj -c Release -o release --nologo --no-restore
      # changes the base-tag in index.html from '/' to 'BlazorGitHubPagesDemo' to match GitHub Pages repository subdirectory
    - name: Change base-tag in index.html from / to MdIcons.Blazor
      run: sed -i 's/<base href="\/" \/>/<base href="\/MdIcons.Blazor\/" \/>/g' release/wwwroot/index.html
     # add .nojekyll file to tell GitHub pages to not treat this as a Jekyll project. (Allow files and folders starting with an underscore)
    - name: Add .nojekyll file
      run: touch release/wwwroot/.nojekyll
    - name: Commit wwwroot to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@3.7.1
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages
        FOLDER: release/wwwroot
